name: Get Feed

on:
  schedule:
    - cron: '0 8 * * *'  # 8 AM UTC (8 AM UK time in winter, 9 AM in summer)
    - cron: '0 17 * * *' # 5 PM UTC (5 PM UK time in winter, 6 PM in summer)
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDS_DATABASE_ID: ${{ secrets.NOTION_FEEDS_DATABASE_ID }}
      RUN_FREQUENCY: 43200 # Adjusted for twice daily runs
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Update Notion Feed
        run: |
          curl -o index.js https://raw.githubusercontent.com/ravgeetdhillon/notion-feeder/build/dist/index.js
          node index.js
